services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - glich-dev

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: glich
      POSTGRES_PASSWORD: glich
      POSTGRES_DB: glich
    networks:
      - glich-dev

volumes:
  postgres-volume:

networks:
  glich-dev:
    driver: bridge
