version: '3'

vars:
  OAPI_CONFIG: "oapi-config.yaml"
  OAPI_SPEC: "docs/swagger-api-v1.yaml"

tasks:
  oapi-generate:
    cmds:
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config={{.OAPI_CONFIG}} {{.OAPI_SPEC}}
